- hosts: hyperfoil_agent
  tasks:
    - name: Print hyperfoil_controller_host
      debug:
        msg: "Controller is {{ hyperfoil_controller_host }}"

- hosts: hyperfoil_agent
  tasks:
    - name: Install Java 17 on agents
      package:
        name: openjdk-17-jre
        state: present
      become: true

- hosts: hyperfoil_controller
  roles:
  - hyperfoil.hyperfoil_setup

- hosts: hyperfoil_agent
  roles:
  - hyperfoil.hyperfoil_test
  vars:
    test_name: my_custom_file

- hosts: hyperfoil_agent
  tasks:
  - name: Find number of requests
    set_fact:
      test_requests: "{{ lookup('csvfile', 'my_custom_file file=/tmp/hyperfoil/workspace/run/' + test_runid + '/stats/total.csv col=2 delimiter=,')}}"
  - name: Print number of requests
    debug:
      msg: "Executed {{ test_requests }} requests."

- hosts: hyperfoil_controller
  roles:
  - hyperfoil.hyperfoil_shutdown
