- name: Install podman
  package:
   name: podman
   state: present
  become: true

- name: Create a directory if it does not exist
  ansible.builtin.file:
   path: /tmp/jfr
   state: directory
   # Have to make global writeable for the user that Infinispan Server creates
   mode: '0777'

