- name: "Initializing hyperfoil agent requirements"
  ansible.builtin.include_tasks: init.yml
  when: operation is undefined or operation == "init"

- name: "Running hyperfoil test"
  ansible.builtin.include_tasks: run.yml
  when: operation is undefined or operation == "run"

- name: "Retrieve stats"
  ansible.builtin.include_tasks: retrieve_stats.yml
  when: operation is undefined or operation == "stats"
